"""Jira Cloud integration — create and update incident tickets.

Credentials are read from environment variables at call time (never at import).
"""

import os

from dotenv import load_dotenv

load_dotenv()

import httpx
import structlog

log = structlog.get_logger(__name__)

_JIRA_BASE_URL = lambda: os.environ["JIRA_BASE_URL"].rstrip("/")
_JIRA_EMAIL = lambda: os.environ["JIRA_EMAIL"]
_JIRA_API_TOKEN = lambda: os.environ["JIRA_API_TOKEN"]
_JIRA_PROJECT_KEY = lambda: os.environ["JIRA_PROJECT_KEY"]

_SEVERITY_TO_PRIORITY = {
    "p1": "Highest",
    "p2": "High",
    "p3": "Medium",
    "p4": "Low",
}


def create_jira_issue(
    alert_id: str,
    alarm_name: str,
    severity: str,
    service_type: str,
    root_cause: str,
    contributing_factors: list[str],
    actions_taken: list[str],
    resolved: bool,
    account_id: str,
    region: str,
) -> dict:
    """Create a Jira incident ticket for a triaged alert.

    Returns dict with 'issue_key' on success, or 'status': 'error' on failure.
    """
    summary = f"[{severity.upper()}] {alarm_name} — {service_type.upper()} alert"
    description = _build_description(
        alert_id=alert_id,
        root_cause=root_cause,
        contributing_factors=contributing_factors,
        actions_taken=actions_taken,
        resolved=resolved,
        account_id=account_id,
        region=region,
    )
    payload = {
        "fields": {
            "project": {"key": _JIRA_PROJECT_KEY()},
            "summary": summary,
            "description": {"type": "doc", "version": 1, "content": [
                {"type": "paragraph", "content": [{"type": "text", "text": description}]}
            ]},
            "issuetype": {"name": os.environ.get("JIRA_ISSUE_TYPE", "Task")},
            "priority": {"name": _SEVERITY_TO_PRIORITY.get(severity.lower(), "Medium")},
            "labels": [f"argos", f"severity-{severity.lower()}", service_type.lower()],
        }
    }
    return _post_to_jira("/rest/api/3/issue", payload, alert_id=alert_id)


def update_jira_issue(issue_key: str, comment: str, alert_id: str) -> dict:
    """Append a comment to an existing Jira issue.

    Returns dict with 'status': 'ok' on success, or 'status': 'error' on failure.
    """
    payload = {
        "body": {"type": "doc", "version": 1, "content": [
            {"type": "paragraph", "content": [{"type": "text", "text": comment}]}
        ]}
    }
    return _post_to_jira(f"/rest/api/3/issue/{issue_key}/comment", payload, alert_id=alert_id)


def _build_description(
    alert_id: str,
    root_cause: str,
    contributing_factors: list[str],
    actions_taken: list[str],
    resolved: bool,
    account_id: str,
    region: str,
) -> str:
    """Build a formatted incident description string."""
    factors = "\n".join(f"  - {f}" for f in contributing_factors) or "  None identified"
    actions = "\n".join(f"  - {a}" for a in actions_taken) or "  None taken"
    status = "RESOLVED" if resolved else "OPEN — requires manual investigation"
    return (
        f"Alert ID: {alert_id}\n"
        f"Account: {account_id} | Region: {region}\n\n"
        f"Root Cause:\n  {root_cause}\n\n"
        f"Contributing Factors:\n{factors}\n\n"
        f"Actions Taken by Argos:\n{actions}\n\n"
        f"Resolution Status: {status}\n\n"
        f"— Auto-generated by Argos"
    )


def _post_to_jira(path: str, payload: dict, alert_id: str) -> dict:
    """POST to the Jira REST API and return the parsed response.

    Returns structured dict with 'status': 'ok' or 'status': 'error'.
    """
    url = f"{_JIRA_BASE_URL()}{path}"
    try:
        response = httpx.post(
            url,
            json=payload,
            auth=(_JIRA_EMAIL(), _JIRA_API_TOKEN()),
            headers={"Accept": "application/json", "Content-Type": "application/json"},
            timeout=15,
        )
        response.raise_for_status()
        data = response.json()
        log.info("jira_post_success", path=path, alert_id=alert_id,
                 issue_key=data.get("key", "N/A"))
        return {"status": "ok", "issue_key": data.get("key"), "id": data.get("id")}
    except httpx.HTTPStatusError as e:
        log.error("jira_http_error", path=path, alert_id=alert_id,
                  status_code=e.response.status_code, error=e.response.text)
        return {"status": "error", "error": str(e), "response": e.response.text}
    except Exception as e:
        log.error("jira_unexpected_error", path=path, alert_id=alert_id, error=str(e))
        return {"status": "error", "error": str(e)}
